apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1  # Adjust based on load
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest  # Replace with your actual image
          ports:
            - containerPort: 50051  # gRPC default port
          env:
            - name: INVENTORY_SERVICE_HOST
              value: "inventory-service"
            - name: PAYMENT_SERVICE_HOST
              value: "payment-service"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 3
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  clusterIP: None  # Enables headless service for internal discovery
