apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50052
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
#          livenessProbe:
#            exec:
#              command: ["grpc_health_probe", "-addr=:50052"]
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          readinessProbe:
#            exec:
#              command: ["grpc_health_probe", "-addr=:50052"]
#            initialDelaySeconds: 3
#            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - port: 50052
      targetPort: 50052
      nodePort: 30052
  type: NodePort